language: ruby
arch:
  - amd64le
  - ppc64le
sudo: false
dist: trusty

script: bundle exec rake test

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-head
matrix:
  include:
    - rvm: 2.4
      env: COVERAGE=true
    - rvm: 2.4
      arch: ppc64le
      env: COVERAGE=true
